version: '3'
services:
  app:
    build:
      context: .
    container_name: smithwatr
    image: dimus/smithwatr
    depends_on:
      - pg
    env_file: .env
  pg:
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
    external: false
